- name: Import data to database
  hosts: dbservers
  vars_files:
    - "../group_vars/db_secrets.yaml"
  tasks:
    - name: ensure python3 and pip are installed
      ansible.builtin.dnf:
        update_cache: yes
        name:
          - python3
          - python3-pip
        state: present
      become: true
      when: ansible_distribution in ["AlmaLinux"]
    
    - name: install mysql-connector-python module
      command: pip3 install mysql-connector-python    
    
    - name: import data to MySQL db
      mysql_import:
        user: "{{ mysql_user }}"
        password: "{{ mysql_password }}"
        host: "localhost"
      notify: notify import DB unsccessfully
  handlers:
    - name: notify import DB usccessfully
      command: echo "Import data to db successfully" >> result.txt
