- name: Import data to database
  hosts: dbservers
  vars_files:
    - "../group_vars/db_secrets.yaml"
  tasks:
    - name: Ensure python3 and pip are installed
      ansible.builtin.dnf:
        update_cache: yes
        name:
          - python3
          - python3-pip
        state: present
      become: true
      when: ansible_distribution in ["AlmaLinux"]
    
    - name: Install mysql-connector-python module
      command: pip3 install mysql-connector-python    
    
    - name: Import data to MySQL db
      mysql_import:
        user: "{{ mysql_user }}"
        password: "{{ mysql_password }}"
    
    - name: Copy test.txt file to server
      ansible.builtin.copy:
        src: test.txt
        dest: "/home/{{ ansible_user }}/test.txt"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0700'
